 # 🐼 Pandas — Table of Contents

```text
                         ┌─────────────────────┐
                         │       PANDAS        │
                         │  Data Analysis Tool │
                         └──────────┬──────────┘
                                    │
        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌───────────────┐           ┌────────────────┐          ┌─────────────────┐
│ 1. Introduction│           │ 2. Data        │          │ 3. Reading &    │
│    to Pandas   │           │    Structures  │          │    Writing Data │
└───────┬────────┘           └───────┬────────┘          └────────┬────────┘
        │                            │                            │
        ▼                            ▼                            ▼
  • What is Pandas            • Series (1D)                • CSV
  • Why Pandas?               • DataFrame (2D)              • Excel
  • Installation              • Creating DataFrame           • JSON
  • import pandas as pd       • Creating Series              • Text files


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 4. Exploring    │        │ 5. Selecting    │         │ 6. Filtering    │
│    Data         │        │    Data         │         │    Data         │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • head()                   • Select columns            • Conditions
   • tail()                   • Select rows               • Boolean indexing
   • shape                    • loc[]                     • Multiple conditions
   • info()                   • iloc[]                    • isin()
   • describe()               • at / iat                  • Text filtering


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 7. Missing Data │        │ 8. Data         │         │ 9. Grouping &   │
│                 │        │    Manipulation │         │    Aggregation  │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • isnull()                 • Add columns              • groupby()
   • notnull()                • Rename columns            • sum()
   • dropna()                 • Drop columns              • mean()
   • fillna()                 • Apply functions            • count()
   • replace()                • Sorting                    • Multiple aggregations


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 10. Merging &   │        │ 11. Time Series │         │ 12. Real-World  │
│     Joining     │        │     Data        │         │     Projects    │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • merge()                  • Datetime                  • Data Cleaning
   • join()                   • to_datetime()             • EDA
   • concat()                 • Date operations            • Data Analysis
   • Join types               • Resampling                • Data Visualization
                              • Time-based filtering       • Real-world datasets


                         ┌─────────────────────┐
                         │   PANDA'S GOAL      │
                         │                     │
                         │ Data → Clean →      │
                         │ Analyze → Insights  │
                         └─────────────────────┘
```

# <h1 style="color:pink">***Chapter-01:Introduction to pandas***</h1>

## 1) what is pandas

## 2)why pandas

## 3) installation of pandas

# <h1 style=color:pink>***Chapter-02 : Data structure in pandas***</h1>

## <h1 style=color:yellow>***1) pandas series:***</h1>A Pandas Series is a one-dimensional, labeled array capable of holding any data type 


```
0    2
1    3
2    4
3    5
4    6

It looks like  single column in an Excel spreadsheet or a database table.

By default, Pandas creates a numeric index starting from 0.

if we want diffrent index instead of numeric then we can give extra parameter index while creating a series 


```

In [2]:
# creating a panads series using list 
import pandas as pd 
ser=pd.Series([2,3,4,5,6])
print(ser)

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [9]:
# using array
import pandas as pd 
import array 
my_arr=array.array("i",[2,3,4,5,6])
print(pd.Series(my_arr))

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [6]:
# using numpy array
import numpy as np 
import pandas as pd 

my_arr=np.array([2,3,1,8])
print(pd.Series(my_arr))

0    2
1    3
2    1
3    8
dtype: int64

In [13]:
# using dictinary 
import pandas as pd 

pd.Series({
      "name":"shahid",
      "age":24,
      "college":"IIT"
})

name       shahid
age            24
college       IIT
dtype: object

## Question practice

In [17]:
# ques1: cretae a series with custom name instead of numeric index index 

import numpy as np 
import pandas as pd 
my_arr=np.array([2,3,1,8])
print(pd.Series(my_arr,index=["a","b","c","d"]))

a    2
b    3
c    1
d    8
dtype: int64

In [1]:
# ques2: create a series using dict and observed the index of series

import pandas as pd 

pd.Series({
      "name":"shahid",
      "age":24,
      "college":"IIT"
})

# index will be the key of dict

name       shahid
age            24
college       IIT
dtype: object

In [ ]:
## ques: can we create series using multidimentinal list or array
ans:no bcz seris is a one dimentinal array so while creating it we must pass a one dimentinal list,array

## 2) Data frame in pandas 

## Pandas DataFrame is a two-dimensional, tabular data structure
## Think of it exactly like a spreadheet / Excel sheet or a SQL database table


## default index(label) of row is numeric starting with 0

In [10]:
# creating dataframes using dict 

import pandas as pd

my_dic = { "name": ["shahid","raj","rakesh"], "age": [24,30,35], "sallary": [40000,30000,45000] }
df = pd.DataFrame(my_dic)
print(df)

     name  age  sallary
0  shahid   24    40000
1     raj   30    30000
2  rakesh   35    45000

In [11]:
# creating data frames using list 
import pandas as pd
my_list=[["shahid","raj","rakesh"],[24,30,35],[40000,35000,45000]]
pd.DataFrame(my_list)

        0      1       2
0  shahid    raj  rakesh
1      24     30      35
2   40000  35000   45000

In [13]:
# now we can give the custom labels to rows and columns 
import pandas as pd
my_list=[["shahid","raj","rakesh"],[24,30,35],[40000,35000,45000]]
pd.DataFrame(my_list,columns=["name","age","sallery"])
pd.DataFrame(my_list,columns=["name","age","sallery"],index=["a","b","c"])

     name    age sallery
a  shahid    raj  rakesh
b      24     30      35
c   40000  35000   45000

In [2]:
# creating a data frames by reading a csv file 
import pandas as pd 

df=pd.read_csv("train.csv")
print(df)

     PassengerId  Survived  Pclass                                               Name     Sex  ...  Parch            Ticket     Fare Cabin  Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  ...      0         A/5 21171   7.2500   NaN         S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  ...      0          PC 17599  71.2833   C85         C
2              3         1       3                             Heikkinen, Miss. Laina  female  ...      0  STON/O2. 3101282   7.9250   NaN         S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  ...      0            113803  53.1000  C123         S
4              5         0       3                           Allen, Mr. William Henry    male  ...      0            373450   8.0500   NaN         S
..           ...       ...     ...                                                ...     ...  ...    ...               ...      ...   ...       ...
886          887         0       2                              Montvila, Rev. Juozas    male  ...      0            211536  13.0000   NaN         S
887          888         1       1                       Graham, Miss. Margaret Edith  female  ...      0            112053  30.0000   B42         S
888          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female  ...      2        W./C. 6607  23.4500   NaN         S
889          890         1       1                              Behr, Mr. Karl Howell    male  ...      0            111369  30.0000  C148         C
890          891         0       3                                Dooley, Mr. Patrick    male  ...      0            370376   7.7500   NaN         Q

[891 rows x 12 columns]

# Exploring the data in data frames

a)Head()

b)Tail()

In [ ]:
c)Sample()

e)info()

f)shape()

g)describe()

# <h1 style=color:pink>***Selecting the data***</h1>

## Selecting Columns

```
df["column_name"]        # Single column (as Series)
df[["col1", "col2"]]     # Multiple columns (as DataFrame)

## Selecting Rows

```
Use .loc[] (label-based) and .iloc[] (position-based):

df.loc[0]                # First row (by label)
df.iloc[0]               # First row (by position)

## select a cell

## slicing

## Fast Access: .at and .iat
## These are optimized for single element or cell  access:

```
df.at[0, "Name"]       # Fast label-based access
df.iat[0, 1]           # Fast position-based access