 # 🐼 Pandas — Table of Contents

```text
                         ┌─────────────────────┐
                         │       PANDAS        │
                         │  Data Analysis Tool │
                         └──────────┬──────────┘
                                    │
        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌───────────────┐           ┌────────────────┐          ┌─────────────────┐
│ 1. Introduction│           │ 2. Data        │          │ 3. Reading &    │
│    to Pandas   │           │    Structures  │          │    Writing Data │
└───────┬────────┘           └───────┬────────┘          └────────┬────────┘
        │                            │                            │
        ▼                            ▼                            ▼
  • What is Pandas            • Series (1D)                • CSV
  • Why Pandas?               • DataFrame (2D)              • Excel
  • Installation              • Creating DataFrame           • JSON
  • import pandas as pd       • Creating Series              • Text files


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 4. Exploring    │        │ 5. Selecting    │         │ 6. Filtering    │
│    Data         │        │    Data         │         │    Data         │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • head()                   • Select columns            • Conditions
   • tail()                   • Select rows               • Boolean indexing
   • shape                    • loc[]                     • Multiple conditions
   • info()                   • iloc[]                    • isin()
   • describe()               • at / iat                  • Text filtering


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 7. Missing Data │        │ 8. Data         │         │ 9. Grouping &   │
│                 │        │    Manipulation │         │    Aggregation  │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • isnull()                 • Add columns              • groupby()
   • notnull()                • Rename columns            • sum()
   • dropna()                 • Drop columns              • mean()
   • fillna()                 • Apply functions            • count()
   • replace()                • Sorting                    • Multiple aggregations


        ┌───────────────────────────┼───────────────────────────┐
        │                           │                           │
        ▼                           ▼                           ▼
┌─────────────────┐        ┌─────────────────┐         ┌─────────────────┐
│ 10. Merging &   │        │ 11. Time Series │         │ 12. Real-World  │
│     Joining     │        │     Data        │         │     Projects    │
└────────┬────────┘        └────────┬────────┘         └────────┬────────┘
         │                          │                           │
         ▼                          ▼                           ▼
   • merge()                  • Datetime                  • Data Cleaning
   • join()                   • to_datetime()             • EDA
   • concat()                 • Date operations            • Data Analysis
   • Join types               • Resampling                • Data Visualization
                              • Time-based filtering       • Real-world datasets


                         ┌─────────────────────┐
                         │   PANDA'S GOAL      │
                         │                     │
                         │ Data → Clean →      │
                         │ Analyze → Insights  │
                         └─────────────────────┘
```

# Chapter-01:Introduction to pandas

## 1) what is pandas

## 2)why pandas

## 3) installation of pandas

# Chapter-02 : Data structure in pandas

## 1) series:A Pandas Series is a one-dimensional, labeled array capable of holding any data type 


```
0    2
1    3
2    4
3    5
4    6
```


##  Think of it like a single column in an Excel spreadsheet or a database table.


## By default, Pandas creates a numeric index starting from 0.

## if we want diffrent index instead of numeric then we can give extra parameter index while creating a series 

## index is a A list of labels that identify each value

In [2]:
# creating a series data structure using list 
import pandas as pd 
ser=pd.Series([2,3,4,5,6])
print(ser)

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [9]:
# using array
import pandas as pd 
import array 
my_arr=array.array("i",[2,3,4,5,6])
print(pd.Series(my_arr))

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [6]:
# using numpy array
import numpy as np 
import pandas as pd 

my_arr=np.array([2,3,1,8])
print(pd.Series(my_arr))

0    2
1    3
2    1
3    8
dtype: int64

In [13]:
# using dictinary 
import pandas as pd 

pd.Series({
      "name":"shahid",
      "age":24,
      "college":"IIT"
})

name       shahid
age            24
college       IIT
dtype: object

## Question practice

In [17]:
# cretae a series with custom name instead of numeric index index 

import numpy as np 
import pandas as pd 

my_arr=np.array([2,3,1,8])
print(pd.Series(my_arr,index=["a","b","c","d"]))

a    2
b    3
c    1
d    8
dtype: int64

In [1]:
# create a series using dict and observed the index of series

import pandas as pd 

pd.Series({
      "name":"shahid",
      "age":24,
      "college":"IIT"
})

# index will be the key of dict

name       shahid
age            24
college       IIT
dtype: object

In [ ]:
## can we create series using multidimentinal list,abytearray
ans:no bcz seris is a one dimentinal array so while creating it we must pass a one dimentinal list,array

## 2) Data frame in pandas 

## Pandas DataFrame is a two-dimensional, tabular data structure
## Think of it exactly like a spreadheet / Excel sheet or a SQL database table


## default index(label) of row is numeric starting with 0

In [10]:
# creating dataframes using dict 

import pandas as pd

my_dic = { "name": ["shahid","raj","rakesh"], "age": [24,30,35], "sallary": [40000,30000,45000] }
df = pd.DataFrame(my_dic)
print(df)

     name  age  sallary
0  shahid   24    40000
1     raj   30    30000
2  rakesh   35    45000

In [11]:
# creating data frames using list 
my_list=[["shahid","raj","rakesh"],[24,30,35],[40000,35000,45000]]
pd.DataFrame(my_list)

        0      1       2
0  shahid    raj  rakesh
1      24     30      35
2   40000  35000   45000

In [13]:
# now we can give the custom labels to rows and columns 

my_list=[["shahid","raj","rakesh"],[24,30,35],[40000,35000,45000]]
pd.DataFrame(my_list,columns=["name","age","sallery"])
pd.DataFrame(my_list,columns=["name","age","sallery"],index=["a","b","c"])

     name    age sallery
a  shahid    raj  rakesh
b      24     30      35
c   40000  35000   45000

# Exploring the data in data frames

# Selecting the data

# Filtering the data